local menu = menu("MarksmanAIOCaitlyn", "Marksman - ".. player.charName)
menu:menu('combo', 'Combo Settings')
menu.combo:menu('qsettings', "Q Settings")
    menu.combo.qsettings:boolean("qcombo", "Use Q", true)
    menu.combo.qsettings:boolean("qmob", "Use Q if enemy is mobilized", true)
    menu.combo.qsettings:boolean("qonly", "Use Q only out-range", true)
    menu.combo.qsettings:slider("mana_mngr", "Minimum Mana %", 15, 0, 100, 5)
menu.combo:menu('wsettings', "W Settings")
    menu.combo.wsettings:boolean("wcombo", "Use W", true)
    menu.combo.wsettings:boolean("CCcombo", "Use W is CC", true)
    menu.combo.wsettings:slider("mana_mngr", "Minimum Mana %", 25, 0, 100, 5)
menu.combo:menu('esettings', "E Settings")
    menu.combo.esettings:boolean("ecombo", "Use E", true)
    menu.combo.esettings:slider("mana_mngr", "Minimum Mana %", 0, 0, 100, 5)
    menu.combo.esettings:header('Another', "Misc Settings")
    menu.combo.esettings:boolean("ecombo", "Use E In Dashing", true)
menu.combo:menu('rsettings', "R Settings")
    menu.combo.rsettings:boolean("rcombo", "Use R", true)
    menu.combo.rsettings:header('Another', "Misc Settings")
    menu.combo.rsettings:boolean("safe", "Use Safe Range", true)
    menu.combo.rsettings:slider("Rrange", "Safe. R Range", 950, 1, 5000, 1);
    menu.combo.rsettings:menu("blacklist", "Blacklist!")
    for i=0, objManager.enemies_n-1 do
        local enemy = objManager.enemies[i]
        if enemy then 
            menu.combo.rsettings.blacklist:boolean(enemy.charName, "Do not use R on: " .. enemy.charName, false)
        end
    end 
menu:menu('harass', 'Hybrid/Harass Settings')
    menu.harass:menu('qsettings', "Q Settings")
        menu.harass.qsettings:boolean("qharras", "Use Q", true)
        menu.harass.qsettings:slider("mana_mngr", "Minimum Mana %", 25, 0, 100, 5)

menu:menu('lane', 'Lane Clear Settings')
        menu.lane:boolean("useQ", "Use Q", true)
        --menu.lane:boolean("useW", "Use W", true)
        menu.lane:slider("mana_mngr", "Minimum Mana %", 45, 0, 100, 5)
menu:header("", "Misc Settings")
       -- menu:keybind("autoe", "Auto E", nil, 'G')
        --menu:keybind("semir", "Semi - R", 'T', nil)
        menu:menu('Flee', 'Flee Settings')
        menu.Flee:keybind("keyjump", "Flee", 'Z', nil)
        menu.Flee:boolean("fleeE", "Use E Flee", true)
        menu.Flee:slider("mana_mngr", "Minimum Health % <", 25, 0, 100, 5)
        menu:menu('kill', 'KillSteal Settings')
            menu.kill:boolean("qkill", "Use Q if KillSteal", true)
            menu.kill:boolean("ekill", "Use E if KillSteal", true)
            menu.kill:boolean("rkill", "Use R if KillSteal", true)
menu:menu("draws", "Drawings")
        menu.draws:boolean("qrange", "Draw Q Range", true)
        menu.draws:color("qcolor", "Q Drawing Color", 255, 255, 255, 255)
        menu.draws:boolean("wrange", "Draw W Range", false)
        menu.draws:color("wcolor", "W Drawing Color", 255, 255, 255, 255)
        menu.draws:boolean("erange", "Draw E Range", false)
        menu.draws:color("ecolor", "E Drawing Color", 255, 255, 255, 255)
        menu.draws:boolean("r_range", "Draw R Range", true)
        menu.draws:color("r", "R Drawing Color", 255, 255, 255, 255)


return menu